(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){dpi=window.devicePixelRatio;var a='data-src';var e=document.querySelector('.un22 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/1.-biolgical-atavistic-736.png':'images/1.-biolgical-atavistic-368.png');
var a='data-src';var e=document.querySelector('.un22 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/2.-biolgical-brain-abnoramilties-and-biochemical-732.png':'images/2.-biolgical-brain-abnoramilties-and-biochemical-366.png');
var a='data-src';var e=document.querySelector('.un22 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/3.-biolgical-twin-studies-and-xyy-734.png':'images/3.-biolgical-twin-studies-and-xyy-367.png');
var a='data-src';var e=document.querySelector('.un22 .slide3');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/4.-individualistic-learning-theory-726.png':'images/4.-individualistic-learning-theory-363.png');
var a='data-src';var e=document.querySelector('.un22 .slide4');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/5.-individualistic-psychodynamic-and-bowlby-730.png':'images/5.-individualistic-psychodynamic-and-bowlby-365.png');
var a='data-src';var e=document.querySelector('.un22 .slide5');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/6.-individualistic-psycholgoical-theory-eysenck-723.png':'images/6.-individualistic-psycholgoical-theory-eysenck-362.png');
var a='data-src';var e=document.querySelector('.un22 .slide6');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/7.-sociological-functionalism-727.png':'images/7.-sociological-functionalism-363.png');
var a='data-src';var e=document.querySelector('.un22 .slide7');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/8.-sociological-marxism-720.png':'images/8.-sociological-marxism-360.png');
var a='data-src';var e=document.querySelector('.un22 .slide8');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/9.-sociological-interactionist-theories-and-labelling-710.png':'images/9.-sociological-interactionist-theories-and-labelling-355.png');
var a='data-src';var e=document.querySelector('.un22 .slide9');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/10.-sociological-realist-theories-701.png':'images/10.-sociological-realist-theories-350.png');};
if(!window.HTMLPictureElement){r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var l=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));l||(l=1);var n=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];o=(n.getBoundingClientRect().top+pageYOffset)*l}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var r=pageYOffset,a=null;requestAnimationFrame(function e(t){a||(a=t);var l=t-a;scrollTo(0,r<o?(o-r)*l/400+r:r-(r-o)*l/400),l<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
initMenu($('#m13')[0]);
$('.un22 .slider').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,overflow: 'hidden',fade: true,slide: 'div',cssEase: 'linear',speed: 300,dots: false,arrows: true,infinite: true});if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"complete"!=document.readyState&&setTimeout(o,100)};o()}

});